server:
  port: 8080



logging:
  level:
    org.springframework.web.servlet.resource: DEBUG
    org.dromara.trans.listener.TransMessageListener: error

spring:
  application:
    name: xinsheng-think-tank-backend
  datasource:
    dynamic:
      primary: master   # 这里指定主数据源名字
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://114.66.28.183:13306/xinsheng-think-tank?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
          username: admin
          password: 123456
  main:
    banner-mode: console
  banner:
    charset: UTF-8
  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 10GB
  # 返回结果_命名
#  jackson:
#    property-naming-strategy: SNAKE_CASE
# 数据源
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true      # 驼峰映射
    cache-enabled: false                     # 是否启用二级缓存
    call-setters-on-nulls: true              # 对 null 字段调用 setter
    lazy-loading-enabled: false              # 是否开启延迟加载
    default-statement-timeout: 30            # SQL 超时（秒）
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 日志实现
  # 全局配置
  global-config:
    banner: true                       # 是否打印 MyBatis-Plus LOGO
    db-config:
      id-type: ASSIGN_ID                     # 主键生成策略：AUTO, INPUT, ASSIGN_ID, ASSIGN_UUID, NONE
      table-prefix: t_                  # 表名前缀
      table-underline: true             # 开启下划线转驼峰
      logic-delete-field: deleted       # 逻辑删除字段名
      logic-delete-value: 1             # 已删除值
      logic-not-delete-value: 0         # 未删除值
# 自动建表
auto-table:
  enable: true                                # 是否开启自动建表
  show-banner: true                           # 是否打印 banner
  model-package: com.tracker.*.models.entity  # 指定实体类所在包路径
  auto-build-database: true                   # 是否自动建表
  init-data:
    enable: true
    base-path: classpath:sql
  mysql:
    table-default-charset: utf8mb4               # 表默认字符集
    table-default-collation: utf8mb4_general_ci  # 表默认排序规则
    column-default-charset: utf8mb4              # 列默认字符集
    column-default-collation: utf8mb4_general_ci # 列默认排序规则

# 数据翻译
easy-trans:
  is-enable-global: true

# 配置接口文档
springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  # SpringDoc 配置属性
  configs:
    title: 信胜智库
    description: 信胜智库
    version: 1.0.0
    author: Hery
    url:
    email: admin@edu.com
    license: Apache License 2.0
    license-url: https://www.apache.org/licenses/LICENSE-2.0

knife4j:
  enable: false

# Minio 配置
minio:
  endpoint: http://114.66.28.183:9000
  bucketName: teaching-resource-repo
  access-key: minio
  secret-key: minio.hery



file:
  upload-dir: C:/Users/Hry/IdeaProjects/xinsheng-think-tank #挂载修改文件存储位置
  # upload-dir: /  #挂载修改文件存储位置

host: http://114.66.28.186:34597


# maxkb工作流配置
maxkb:
  host: http://118.31.60.195:8080
  api-key: application-6fcc3979c54aa8dd2c17411d4f471862
  api-path:
    upload: /chat/api/oss/file
    chat-id: /chat/api/chat_message/chat_id
    chat: /chat/api/open



# jwt配置
jwt:
  secret: learn-xinsheng-think-tank-super-secret-key-32bytes-minimum
  access-token:
    default-expire-seconds: 86400
  refresh-token:
    default-expire-seconds: 2592000
  whitelist:
    - /api/v1/user/auth
    - /api/v1/user/login
    - /api/v1/user/check
    - /doc.html
    - /favicon.ico
    - /v3/api-docs/**
    - /api/v1/wiki/add-view
    - /api/v1/search/search
    - /api/v1/search/random-recommend
    - /api/v1/system/**
    - /api/v1/comments/list
    - /files/**
    - /api/v1/wiki/entries
    - /api/v1/wiki/entry

