package com.learn.controller;

import com.learn.domain.dto.MaxKBChatMessageDTO;
import com.learn.domain.pojo.Result;
import com.learn.service.maxkb.MaxKbService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.annotation.Resource;
import java.util.HashMap;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.multipart.MultipartFile;
import reactor.core.publisher.Flux;

@Tag(name="ai生成词条")
@RestController
@RequestMapping(value={"/api/v1/ai"})
@Validated
public class MaxKBController {
    @Resource
    private MaxKbService maxKbService;

    @PostMapping(value={"/creat-entry"})
    @Operation(summary="AI创建词条")
    public Result<HashMap<Object, Object>> approval(@RequestParam String title, @RequestParam(required=false) String prompt, @RequestParam(value="files") MultipartFile multipartFile) {
        String s = this.maxKbService.aiCreateEntry(title, prompt, multipartFile);
        HashMap<String, String> map = new HashMap<String, String>();
        map.put("aiCreatId", s);
        return Result.success(map);
    }

    @PostMapping(value={"/upload"})
    @Operation(summary="AI上传文件")
    public Result<MaxKBChatMessageDTO.DocumentInfo> upload(@RequestParam String source_type, @RequestParam String source_id, @RequestParam(value="file") MultipartFile multipartFile) {
        MaxKBChatMessageDTO.DocumentInfo res = this.maxKbService.uploadFileToMaxKBAndBuildInfo(multipartFile);
        return Result.success(res);
    }

    @GetMapping(value={"/get-chat-id"})
    @Operation(summary="获取chat_id")
    public Result<String> getChatId() {
        String chatId = this.maxKbService.getChatId();
        return Result.success(chatId);
    }

    @PostMapping(value={"/chat"})
    @Operation(summary="AI聊天")
    public Result<String> chat(@RequestBody MaxKBChatMessageDTO maxKBChatMessageDTO) {
        String res = this.maxKbService.createChat(maxKBChatMessageDTO);
        return Result.success(res);
    }

    @Operation(summary="AI流式聊天")
    @PostMapping(value={"/stream"}, produces={"text/event-stream"})
    public Flux<Object> chatStream(@RequestBody MaxKBChatMessageDTO chatMessageDTO) {
        chatMessageDTO.setStream(true);
        return this.maxKbService.streamChat(chatMessageDTO);
    }

    @Operation(summary="AI同步聊天")
    @PostMapping(value={"/chat-sync"})
    public Result<String> chatSync(@RequestBody MaxKBChatMessageDTO chatMessageDTO) {
        String res = this.maxKbService.chatSync(null, chatMessageDTO);
        return Result.success(res);
    }

    @GetMapping(path={"/auto-generated-entry"})
    @Operation(summary="AI流式返回词条")
    public Result<HashMap<String, Object>> autoGeneratedEntry(@RequestParam(value="aiCreatId") String thinkTankId) {
        Result fluxContent = this.maxKbService.getFluxContent(thinkTankId);
        return fluxContent;
    }
}
